# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HealthApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HealthApp

  target 'HealthApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNSVG', :path => '../node_modules/react-native-svg'

  end

  target 'HealthAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HealthApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HealthApp-tvOS

  target 'HealthApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
